// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdo3BSIe9uxDtkan_0nxBBGxoEajBr4Ag',
    appId: '1:490930282376:web:7f269cb60b8ad0d6a8e43d',
    messagingSenderId: '490930282376',
    projectId: 'person-note-d625a',
    authDomain: 'person-note-d625a.firebaseapp.com',
    databaseURL: 'https://person-note-d625a-default-rtdb.firebaseio.com',
    storageBucket: 'person-note-d625a.appspot.com',
    measurementId: 'G-MPDLB94TFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2aF_jGfpj_eUdxovtLryf1HoaP8_3_8s',
    appId: '1:490930282376:android:dfad7d885a37d881a8e43d',
    messagingSenderId: '490930282376',
    projectId: 'person-note-d625a',
    databaseURL: 'https://person-note-d625a-default-rtdb.firebaseio.com',
    storageBucket: 'person-note-d625a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBODxBgXdqEM4B_xA4E7dsmbZ9VqhrCQjE',
    appId: '1:490930282376:ios:65a4c02c2cb8ce31a8e43d',
    messagingSenderId: '490930282376',
    projectId: 'person-note-d625a',
    databaseURL: 'https://person-note-d625a-default-rtdb.firebaseio.com',
    storageBucket: 'person-note-d625a.appspot.com',
    androidClientId: '490930282376-5n7h10e44h5bt9pfidbifh302lnkigd0.apps.googleusercontent.com',
    iosClientId: '490930282376-j8o6qllq1cd7042uhromair1r3fev67s.apps.googleusercontent.com',
    iosBundleId: 'com.example.personMemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBODxBgXdqEM4B_xA4E7dsmbZ9VqhrCQjE',
    appId: '1:490930282376:ios:65a4c02c2cb8ce31a8e43d',
    messagingSenderId: '490930282376',
    projectId: 'person-note-d625a',
    databaseURL: 'https://person-note-d625a-default-rtdb.firebaseio.com',
    storageBucket: 'person-note-d625a.appspot.com',
    androidClientId: '490930282376-5n7h10e44h5bt9pfidbifh302lnkigd0.apps.googleusercontent.com',
    iosClientId: '490930282376-j8o6qllq1cd7042uhromair1r3fev67s.apps.googleusercontent.com',
    iosBundleId: 'com.example.personMemo',
  );
}
